services:
  bot:
    build: .
    container_name: selfie
    restart: always
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env

  mongodb:
    image: mongo:6
    container_name: mongodb-selfie
    restart: always
    ports:
      - '127.0.0.1:27014:27017'
    volumes:
      - mongodb_data:/data/db
    mem_limit: 512m
    command: ['mongod', '--wiredTigerCacheSizeGB=0.256']

  redis:
    image: redis:alpine
    container_name: redis-selfie
    restart: always
    ports:
      - '127.0.0.1:6374:6379'
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
